# Generated by Django 4.2.2 on 2023-06-17 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_webservice', '0004_remove_stock_product_product_stock_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.OneToOneField(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app_webservice.stock'),
        ),
    ]
