# Generated by Django 4.2.2 on 2023-06-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webservice', '0006_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
