# Generated by Django 4.2.2 on 2023-06-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_webservice', '0008_alter_product_stock_alter_stock_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
