# Generated by Django 4.2.2 on 2023-06-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_webservice', '0009_remove_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='product',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
